"""The ccguard git hooks: what install_git_hooks.py writes and push-gate.py checks.

One small script per git hook lives in a stable directory,
${XDG_DATA_HOME:-~/.local/share}/ccguard/git-hooks, so that
`git config --global core.hooksPath <that directory>` survives plugin
updates. Every script first runs the repository's own hook
(<git common dir>/hooks/<name>) if there is one, so setting core.hooksPath
does not switch existing hooks off. `pre-push` additionally runs the ccguard
gate (pre_push_gate.py) when CLAUDECODE=1.

The content is fixed, so it can be compared instead of guessing from command
text whether something wrote to it. The one variable part is the gate path
in `pre-push`: the plugin version that wrote the file puts its own path
there, and two sessions on different versions rewrite it back and forth.
Any installed ccguard gate is accepted there.
"""

import os
import re

HOOKS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GATE = os.path.join(HOOKS, "pre_push_gate.py")
TARGET = os.path.join(
    os.environ.get("XDG_DATA_HOME") or os.path.join(os.path.expanduser("~"), ".local", "share"),
    "ccguard", "git-hooks",
)
HOOK_NAMES = [
    "applypatch-msg", "pre-applypatch", "post-applypatch", "pre-commit", "pre-merge-commit",
    "prepare-commit-msg", "commit-msg", "post-commit", "pre-rebase", "post-checkout",
    "post-merge", "pre-push", "pre-receive", "update", "proc-receive", "post-receive",
    "post-update", "reference-transaction", "push-to-checkout", "pre-auto-gc", "post-rewrite",
    "sendemail-validate", "post-index-change",
]

PASS_THROUGH = """#!/bin/sh
# Generated by ccguard at session start; edits are overwritten.
# Runs the repository's own {name} hook, as git would without core.hooksPath.
d=$(git rev-parse --git-common-dir 2>/dev/null) || exit 0
[ -x "$d/hooks/{name}" ] && exec "$d/hooks/{name}" "$@"
exit 0
"""

PRE_PUSH = """#!/bin/sh
# Generated by ccguard at session start; edits are overwritten.
# For pushes started by Claude Code (CLAUDECODE=1), runs the ccguard gate,
# then the repository's own pre-push hook with the same input.
input=$(cat)
if [ "$CLAUDECODE" = "1" ]; then
  if [ ! -f "{gate}" ]; then
    echo "BLOCKED (ccguard pre-push): the gate script is missing; start a new session." >&2
    exit 1
  fi
  if [ -n "$input" ]; then printf '%s\\n' "$input"; fi | python3 "{gate}" "$@" || exit 1
fi
d=$(git rev-parse --git-common-dir 2>/dev/null) || exit 0
if [ -x "$d/hooks/pre-push" ]; then
  if [ -n "$input" ]; then printf '%s\\n' "$input"; fi | "$d/hooks/pre-push" "$@"
  exit $?
fi
exit 0
"""

# pre-push with the gate path left open; the two occurrences must agree.
_head, _middle, _tail = PRE_PUSH.split("{gate}")
PRE_PUSH_ANY_GATE = re.compile(
    re.escape(_head) + r'([^"\n]+)' + re.escape(_middle) + r"\1" + re.escape(_tail))
PLUGIN_CACHE = os.path.join(
    os.environ.get("CLAUDE_CONFIG_DIR") or os.path.join(os.path.expanduser("~"), ".claude"),
    "plugins", "cache")
# <marketplace>/ccguard/<version>/hooks/pre_push_gate.py under the plugin cache
INSTALLED_GATE = re.compile(r"[^/]+/ccguard/[^/]+/hooks/pre_push_gate\.py")


def expected(name, gate=GATE):
    return PRE_PUSH.format(gate=gate) if name == "pre-push" else PASS_THROUGH.format(name=name)


def gate_ok(gate):
    """This version's gate, or the gate of another installed ccguard version that exists."""
    real = os.path.realpath(gate)
    if real == os.path.realpath(GATE):
        return True
    rel = os.path.relpath(real, os.path.realpath(PLUGIN_CACHE))
    return (not rel.startswith("..") and bool(INSTALLED_GATE.fullmatch(rel.replace(os.sep, "/")))
            and os.path.isfile(real))


def intact(name, text):
    if name != "pre-push":
        return text == expected(name)
    m = PRE_PUSH_ANY_GATE.fullmatch(text)
    return bool(m) and gate_ok(m.group(1))


def changed(target=TARGET):
    """Names of hooks that differ from what ccguard writes, are missing or not executable.

    Empty when the directory does not exist: nothing was installed yet, and
    the SessionStart hook reports that case.
    """
    if not os.path.isdir(target):
        return []
    found = []
    for name in HOOK_NAMES:
        path = os.path.join(target, name)
        try:
            with open(path, encoding="utf-8") as f:
                ok = intact(name, f.read()) and os.access(path, os.X_OK)
        except (OSError, UnicodeDecodeError):
            ok = False
        if not ok:
            found.append(name)
    return found


def write_if_changed(path, text):
    try:
        with open(path, encoding="utf-8") as f:
            if f.read() == text and os.access(path, os.X_OK):
                return
    except (OSError, UnicodeDecodeError):
        pass
    tmp = f"{path}.tmp{os.getpid()}"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.chmod(tmp, 0o755)
    os.replace(tmp, path)


def install(target=TARGET, names=None):
    os.makedirs(target, exist_ok=True)
    for name in names or HOOK_NAMES:
        write_if_changed(os.path.join(target, name), expected(name))
