"""The ccguard git hooks: what install_git_hooks.py writes and push-gate.py checks.

One small script per git hook lives in a stable directory,
${XDG_DATA_HOME:-~/.local/share}/ccguard/git-hooks, so that
`git config --global core.hooksPath <that directory>` survives plugin
updates. Every script first runs the repository's own hook
(<git common dir>/hooks/<name>) if there is one, so setting core.hooksPath
does not switch existing hooks off. `pre-push` additionally runs the ccguard
gate (pre_push_gate.py) when CLAUDECODE=1.

The content is fixed, so it can be compared instead of guessing from command
text whether something wrote to it. Nothing but this version's own text is
accepted: push-gate.py rewrites any difference before every Bash command.
The gate path in `pre-push` is the one part that differs in normal use (two
sessions on different plugin versions, or one run with --plugin-dir, each
write their own), so a difference there alone is rewritten without being
reported; it is never trusted.
"""

import os
import re

HOOKS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GATE = os.path.join(HOOKS, "pre_push_gate.py")
TARGET = os.path.join(
    os.environ.get("XDG_DATA_HOME") or os.path.join(os.path.expanduser("~"), ".local", "share"),
    "ccguard", "git-hooks",
)
HOOK_NAMES = [
    "applypatch-msg", "pre-applypatch", "post-applypatch", "pre-commit", "pre-merge-commit",
    "prepare-commit-msg", "commit-msg", "post-commit", "pre-rebase", "post-checkout",
    "post-merge", "pre-push", "pre-receive", "update", "proc-receive", "post-receive",
    "post-update", "reference-transaction", "push-to-checkout", "pre-auto-gc", "post-rewrite",
    "sendemail-validate", "post-index-change",
]

PASS_THROUGH = """#!/bin/sh
# Generated by ccguard at session start; edits are overwritten.
# Runs the repository's own {name} hook, as git would without core.hooksPath.
d=$(git rev-parse --git-common-dir 2>/dev/null) || exit 0
[ -x "$d/hooks/{name}" ] && exec "$d/hooks/{name}" "$@"
exit 0
"""

PRE_PUSH = """#!/bin/sh
# Generated by ccguard at session start; edits are overwritten.
# For pushes started by Claude Code (CLAUDECODE=1), runs the ccguard gate,
# then the repository's own pre-push hook with the same input.
input=$(cat)
if [ "$CLAUDECODE" = "1" ]; then
  if [ ! -f "{gate}" ]; then
    echo "BLOCKED (ccguard pre-push): the gate script is missing; start a new session." >&2
    exit 1
  fi
  if [ -n "$input" ]; then printf '%s\\n' "$input"; fi | python3 "{gate}" "$@" || exit 1
fi
d=$(git rev-parse --git-common-dir 2>/dev/null) || exit 0
if [ -x "$d/hooks/pre-push" ]; then
  if [ -n "$input" ]; then printf '%s\\n' "$input"; fi | "$d/hooks/pre-push" "$@"
  exit $?
fi
exit 0
"""

# pre-push with another gate path: an absolute path the same in both places,
# without the characters the shell expands inside double quotes. Used only to
# decide whether to report a rewrite.
_head, _middle, _tail = PRE_PUSH.split("{gate}")
PRE_PUSH_OTHER_GATE = re.compile(
    re.escape(_head) + r'(/[^"$`\\\n]+)' + re.escape(_middle) + r"\1" + re.escape(_tail))


def expected(name, gate=GATE):
    return PRE_PUSH.format(gate=gate) if name == "pre-push" else PASS_THROUGH.format(name=name)


def _read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def changed(target=TARGET):
    """Names of hooks that differ from this version's text, are missing or not executable.

    Every hook when the directory itself is missing: the SessionStart hook
    creates it, and git silently runs no hook for a hooksPath that does not
    exist. Anything that cannot be read or compared counts as changed.
    """
    if not os.path.isdir(target):
        return list(HOOK_NAMES)
    found = []
    for name in HOOK_NAMES:
        path = os.path.join(target, name)
        try:
            ok = _read(path) == expected(name) and os.access(path, os.X_OK)
        except Exception:  # noqa: BLE001 - unreadable is changed
            ok = False
        if not ok:
            found.append(name)
    return found


def only_gate_path(name, target=TARGET):
    """True for a pre-push that differs only in the gate path (another version, a dev dir)."""
    if name != "pre-push":
        return False
    path = os.path.join(target, name)
    try:
        return bool(PRE_PUSH_OTHER_GATE.fullmatch(_read(path))) and os.access(path, os.X_OK)
    except Exception:  # noqa: BLE001
        return False


def write_if_changed(path, text):
    try:
        with open(path, encoding="utf-8") as f:
            if f.read() == text and os.access(path, os.X_OK):
                return
    except (OSError, UnicodeDecodeError):
        pass
    tmp = f"{path}.tmp{os.getpid()}"
    try:
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(text)
        os.chmod(tmp, 0o755)
        os.replace(tmp, path)
    except OSError:
        try:
            os.remove(tmp)
        except OSError:
            pass
        raise


def install(target=TARGET, names=None):
    os.makedirs(target, exist_ok=True)
    for name in names or HOOK_NAMES:
        write_if_changed(os.path.join(target, name), expected(name))
