#!/usr/bin/env python3
"""SessionStart: keep the ccguard git hooks directory up to date.

Writes one small script per git hook into a stable directory,
${XDG_DATA_HOME:-~/.local/share}/ccguard/git-hooks, so that
`git config --global core.hooksPath <that directory>` survives plugin
updates. Every script first runs the repository's own hook
(<git common dir>/hooks/<name>) if there is one, so setting core.hooksPath
does not switch existing hooks off. `pre-push` additionally runs the ccguard
gate (pre_push_gate.py from the current plugin version) when CLAUDECODE=1.

Setting core.hooksPath is left to the user: it changes git for every
repository. When it does not point here, the session is told how.
"""

import json
import os
import subprocess
import sys

PLUGIN_HOOKS = os.path.dirname(os.path.abspath(__file__))
GATE = os.path.join(PLUGIN_HOOKS, "pre_push_gate.py")
TARGET = os.path.join(
    os.environ.get("XDG_DATA_HOME") or os.path.join(os.path.expanduser("~"), ".local", "share"),
    "ccguard", "git-hooks",
)
HOOK_NAMES = [
    "applypatch-msg", "pre-applypatch", "post-applypatch", "pre-commit", "pre-merge-commit",
    "prepare-commit-msg", "commit-msg", "post-commit", "pre-rebase", "post-checkout",
    "post-merge", "pre-push", "pre-receive", "update", "proc-receive", "post-receive",
    "post-update", "reference-transaction", "push-to-checkout", "pre-auto-gc", "post-rewrite",
    "sendemail-validate", "post-index-change",
]

PASS_THROUGH = """#!/bin/sh
# Generated by ccguard at session start; edits are overwritten.
# Runs the repository's own {name} hook, as git would without core.hooksPath.
d=$(git rev-parse --git-common-dir 2>/dev/null) || exit 0
[ -x "$d/hooks/{name}" ] && exec "$d/hooks/{name}" "$@"
exit 0
"""

PRE_PUSH = """#!/bin/sh
# Generated by ccguard at session start; edits are overwritten.
# For pushes started by Claude Code (CLAUDECODE=1), runs the ccguard gate,
# then the repository's own pre-push hook with the same input.
input=$(cat)
if [ "$CLAUDECODE" = "1" ]; then
  if [ ! -f "{gate}" ]; then
    echo "BLOCKED (ccguard pre-push): the gate script is missing; start a new session." >&2
    exit 1
  fi
  if [ -n "$input" ]; then printf '%s\\n' "$input"; fi | python3 "{gate}" "$@" || exit 1
fi
d=$(git rev-parse --git-common-dir 2>/dev/null) || exit 0
if [ -x "$d/hooks/pre-push" ]; then
  if [ -n "$input" ]; then printf '%s\\n' "$input"; fi | "$d/hooks/pre-push" "$@"
  exit $?
fi
exit 0
"""


def write_if_changed(path, text):
    try:
        with open(path, encoding="utf-8") as f:
            if f.read() == text and os.access(path, os.X_OK):
                return
    except OSError:
        pass
    tmp = f"{path}.tmp{os.getpid()}"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.chmod(tmp, 0o755)
    os.replace(tmp, path)


def install():
    os.makedirs(TARGET, exist_ok=True)
    for name in HOOK_NAMES:
        text = PRE_PUSH.format(gate=GATE) if name == "pre-push" else PASS_THROUGH.format(name=name)
        write_if_changed(os.path.join(TARGET, name), text)


def configured():
    try:
        value = subprocess.run(["git", "config", "--global", "--get", "core.hooksPath"],
                               capture_output=True, text=True, timeout=5).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return False
    return bool(value) and os.path.realpath(os.path.expanduser(value)) == os.path.realpath(TARGET)


def main():
    try:
        install()
    except OSError as e:
        print(json.dumps({"hookSpecificOutput": {
            "hookEventName": "SessionStart",
            "additionalContext": f"ccguard could not write its git hooks to {TARGET} "
                                 f"({e.__class__.__name__}); pushes are blocked by push-gate.",
        }}))
        return 0
    if not configured():
        print(json.dumps({"hookSpecificOutput": {
            "hookEventName": "SessionStart",
            "additionalContext": "ccguard: the pre-push gate is not active, so push-gate will "
                                 "deny git push. Ask the user to run (once): "
                                 f"git config --global core.hooksPath {TARGET}",
        }}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
